CommitMsg:
  HardTabs:
    enabled: true

PreCommit:
  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/**/*'
      - 'dock/**/*'

  MergeConflicts:
    enabled: true

  PryBinding:
    enabled: true

  RuboCop:
    enabled: true

  ShellCheck:
    enabled: true

  TrailingWhitespace:
    enabled: true

verify_signatures: true
