CommitMsg:
  GerritChangeId:
    enabled: true

  HardTabs:
    enabled: true

PreCommit:
  AuthorEmail:
    enabled: true
    description: 'Checking author email for Brigade domain'
***REMOVED***

  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/**/*'
      - 'dock/**/*'
      - 'jenkins/**/*'
      - 'script/**/*'

  MergeConflicts:
    enabled: true

  ScriptDirModifications:
    enabled: true

  PryBinding:
    enabled: true

  RuboCop:
    enabled: true

  ShellCheck:
    enabled: true

  TrailingWhitespace:
    enabled: true

# This repository is private, so we don't need this additional security
verify_signatures: false
